language: java
sudo: false # faster builds

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

branches: # build only on these branches
  only:
    - master

script:
  # Start Proxy
  - sudo o_o &
  # Test
  - mvn test -B -f pom.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura coveralls:report

matrix:
  allow_failures:
    - jdk: openjdk10
    - jdk: openjdk11